### ISSUE TITLE
Sorting options in web view

### ISSUE THREAD

**Issue by tobiasvl** [JohnEarnest/chip8Archive#16]
I wonder if it would be worthwhile to add other sorting options to the chip8Archive web page?

Sorting by "event" is okay, but being able to sort by "platform" might be more useful if we want emulator developers to include these games in their distributions, which have varying levels of platform support.

**Comment by JohnEarnest** [comment]
Ordering by date of release might make sense. I suppose I could offer sorting games alphabetically, too.

There's already an option to sort by platform. Are you saying that should be the default?

**Comment by tobiasvl** [comment]
Ehm, no, I'd actually not scrolled to the bottom of the page and seen the sorting options. Apologies. That's mostly my fault, but perhaps they could/should be moved to the top so they're more prominent?

**Comment by JohnEarnest** [comment]
Fair enough. Done.
