### ISSUE TITLE
horseyJump.8o

### ISSUE THREAD

**Issue by fabianbuettner** [JohnEarnest/chip8Archive#18]
This does not seem to be a valid chip8 program does it?
It uses 0-byte length sprite to draw the fence and the horse.
Also V5 is assigned twice in the beginning (overwriting hX).

**Comment by TomRintjema** [comment]
0 byte sprites are a superchip feature. Horsey Jump and Horse World Online should both be Superchip games.

**Comment by fabianbuettner** [comment]
ah thanks for the quick reply

**Comment by JohnEarnest** [comment]
Yep, `horseyJump` was miscategorized. Good catch, @fabianbuettner!

**Comment by JohnEarnest** [comment]
(As for the reuse of `v5`, that just looks like an oversight in the program itself. Archived as submitted!)

**Comment by fabianbuettner** [comment]
@JohnEarnest cool, thanks! My chip8 emulator misbehaves with a couple(4-5) of other chip8 roms, but I could not figure it out, yet.
@TomRintjema Horse World Online seems to work with my chip8 emulator
